/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alloba.mono

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun dummyTest(){
        assertTrue(0 == 0)
    }
}
