name: Deploy Personal Site Infra
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tf/personal-landing-site'
      - '.github/workflows/infrastructure.personal-landing-site.yml'

jobs:
  terraform-deploy:
    uses: './.github/workflows/shared.terraform-deploy.yml'
    with:
      target-dir: './tf/personal-landing-site'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1