name: Deploy Central DNS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tf/central-dns'
      - '.github/workflows/infrastructure.central-dns.yml'

jobs:
  terraform-deploy:
    uses: './.github/workflows/shared.terraform-deploy.yml'
    with:
      target-dir: './tf/central-dns'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1