name: Deploy Kaleidoscope Infra
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tf/kaleidoscope'
      - '.github/workflows/kaleidoscope.yml'

jobs:
  terraform-deploy:
    uses: './.github/workflows/shared-infrastructure-deploy.yml'
    with:
      target-dir: './tf/kaleidoscope'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1